"""
Django settings for my_app project.

Generated by 'django-admin startproject' using Django 4.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import uuid
import os
import mongoengine

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-uvvp_x9=5$et%5nh4avc-32!a)#j9knvgq6d2do0fwkj_jo_i='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'my_app',
    # "django_mongoengine",
    # "django_mongoengine.mongo_auth",
    # "django_mongoengine.mongo_admin",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'my_app.middleware.JsonRequestLogMiddleware'
]

ROOT_URLCONF = 'my_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'my_app.wsgi.application'

# MONGODB_DATABASES = {
#     'default': {
#         'host': 'mongodb://localhost:27017/',
#         'db': 'zinc_db'
#     }
# }

# AUTH_USER_MODEL = "mongo_auth.MongoUser"

# AUTHENTICATION_BACKENDS = ("django_mongoengine.mongo_auth.backends.MongoEngineBackend",)

# SESSION_ENGINE = "django_mongoengine.sessions"

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         # 'ENGINE': 'django.db.backends.sqlite3',
#         # 'NAME': BASE_DIR / 'db.sqlite3',
#         'ENGINE': 'django.db.backends.dummy'
#     }
# }
# DATABASES = {"default": {"ENGINE": "django.db.backends.dummy"}}
from django_mongodb_backend import parse_uri

DATABASES = {
    "default": parse_uri(
        "mongodb://localhost:27017", db_name="example"
    ),
}

# import mongoengine
# mongoengine.connect(db='zinc_db', host='mongodb://localhost:27017')

# import mongoengine
# MONGO_DATABASE_HOST = 'mongodb://localhost:27017'
# mongoengine.connect('zinc_db', host=MONGO_DATABASE_HOST)


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') #python manage.py collectstatic

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'json': {
            '()': 'logging.Formatter',
            'format': '%(message)s',  # Our middleware already formats as JSON
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'json',
        },
        # 'file': {
        #     'level': 'INFO',
        #     'class': 'logging.FileHandler',
        #     'filename': 'request.log',
        #     'formatter': 'json',
        # },
    },
    'loggers': {
        'my_app.middleware': {  # Adjust to the location of your middleware
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Root logger (optional, for other logs)
        '': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    },
}
#my constants
FILE_PATH = './my_app/sales.csv'

#Messages
MESSAGES = {
    'ERR_FILE_CONTENT': 'The file content is corrupted or missed.',
    'ERR_UPSERT_PRODUCTS': 'There is an error when inserting the products.',
    'ERR_UPSERT_SALES': 'There is an error when inserting the sales.',
    'ERR_MISSING_DATES': 'Please specify start or end dates',
    'ERR_INVALID_DATES': 'Invalid date format. Please use YYYY-MM-DD.',
    'ERR_INVALID_RANGE_DATES': 'Start date cannot be after end date.'

}

def get_random_uuid():
    return str(uuid.uuid4())