name: CI Workflow

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print Environment Variables (Debug)
        run: env
      
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      #TODO when we have DB server
      #- name: Build Docker image
        #run: docker build --no-cache -t my_app .

      #- name: Run migrations in container
        #run: docker run --rm my_app python manage.py migrate

      #- name: Execute unit tests
        #run: docker run --rm my_app python manage.py test
