name: CI Workflow

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # Or your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        run: docker build --no-cache -t python_django_gunicorn_docker .

      - name: Run migrations in container
        run: docker run --rm my_app python manage.py migrate

      - name: Execute unit tests
        run: docker run --rm my_app python manage.py test
